# Ansible inventory, generated by Terraform.
#
# The `ansible` provider writes ansible_host / ansible_group entries into the
# Terraform state; the cloud.terraform.terraform_provider inventory plugin reads
# that state back, so `ansible/inventory.yml` contains no address and nothing
# ever has to be copied by hand between the two tools. Only non-sensitive facts
# are published here: the database password stays in Secrets Manager and is
# fetched by each instance with its own IAM role.

locals {
  ssh_hardening_args = "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

  # null when the bastion is disabled; coalesce keeps the string interpolation
  # below valid in that case.
  bastion_address = coalesce(module.compute.bastion_public_ip, "bastion-disabled")

  # The application instances have no public address: every SSH session is
  # tunnelled through the bastion.
  bastion_proxy_args = var.enable_bastion ? join(" ", [
    "-o ProxyCommand=\"ssh -W %h:%p -q -i ${local.ssh_private_key_path} ${local.ssh_hardening_args} ubuntu@${local.bastion_address}\"",
    local.ssh_hardening_args,
  ]) : local.ssh_hardening_args

  # Facts every play needs, published once as group variables and repeated as
  # host variables so the inventory is usable even with --limit on a host.
  ansible_common_vars = {
    project_name = var.project_name
    # `environment` is a reserved keyword in Ansible, hence env_name.
    env_name   = var.environment
    aws_region = var.aws_region

    db_host       = module.database.address
    db_port       = tostring(module.database.port)
    db_name       = module.database.database_name
    db_user       = module.database.username
    db_secret_arn = module.database.secret_arn
    db_multi_az   = tostring(module.database.multi_az)

    efs_file_system_id = module.storage.file_system_id
    efs_dns_name       = module.storage.dns_name

    alb_dns_name       = module.loadbalancer.dns_name
    alb_target_group   = module.loadbalancer.target_group_arn
    shop_host          = local.shop_host
    shop_admin_dir     = var.prestashop_admin_dir
    shop_scheme        = local.enable_https ? "https" : "http"
    shop_url           = local.shop_url
    app_instance_count = tostring(local.app_instance_count)
  }
}

resource "ansible_group" "prestashop" {
  name      = "prestashop"
  variables = local.ansible_common_vars
}

resource "ansible_group" "bastion" {
  name = "bastion"
  variables = {
    project_name = var.project_name
    env_name     = var.environment
    aws_region   = var.aws_region
  }
}

resource "ansible_group" "environment" {
  name      = "env_${var.environment}"
  children  = ["prestashop", "bastion"]
  variables = { env_name = var.environment }
}

resource "ansible_host" "app" {
  count = local.app_instance_count

  name   = "${local.name_prefix}-app-${count.index + 1}"
  groups = [ansible_group.prestashop.name, ansible_group.environment.name]

  variables = merge(local.ansible_common_vars, {
    ansible_host                 = module.compute.app_private_ips[count.index]
    ansible_user                 = "ubuntu"
    ansible_ssh_private_key_file = local.ssh_private_key_path
    ansible_ssh_common_args      = local.bastion_proxy_args

    instance_id       = module.compute.app_instance_ids[count.index]
    availability_zone = module.compute.app_availability_zones[count.index]
  })
}

resource "ansible_host" "bastion" {
  count = var.enable_bastion ? 1 : 0

  name   = "${local.name_prefix}-bastion"
  groups = [ansible_group.bastion.name, ansible_group.environment.name]

  variables = {
    ansible_host                 = local.bastion_address
    ansible_user                 = "ubuntu"
    ansible_ssh_private_key_file = local.ssh_private_key_path
    ansible_ssh_common_args      = local.ssh_hardening_args

    instance_id  = module.compute.bastion_instance_id
    project_name = var.project_name
    env_name     = var.environment
    aws_region   = var.aws_region
  }
}
