# Managed MySQL. Running the data store on RDS rather than on EC2 gives us
# automated backups, patching, monitoring and - in production - a synchronous
# standby with automatic failover, none of which we would have to write or
# operate ourselves.

# Stable, unique suffix for the final snapshot: a fixed name would collide with
# the snapshot left behind by a previous deployment of the same environment.
resource "random_id" "snapshot" {
  byte_length = 4
}

# The password travels through a shell, a docker --env-file and PHP before it
# reaches MySQL. Restricting it to characters none of them interpret removes a
# whole class of breakage; 40 characters keep the entropy well above what the
# punctuation added.
resource "random_password" "master" {
  length           = 40
  special          = true
  override_special = "-_."
  min_lower        = 4
  min_upper        = 4
  min_numeric      = 4
  min_special      = 2
}

resource "aws_db_subnet_group" "this" {
  name       = "${var.name_prefix}-db"
  subnet_ids = var.subnet_ids

  tags = merge(var.tags, { Name = "${var.name_prefix}-db-subnet-group" })
}

# PrestaShop stores everything in utf8mb4; setting it at the server level avoids
# per-connection surprises with emoji or accented product names.
resource "aws_db_parameter_group" "this" {
  name_prefix = "${var.name_prefix}-mysql"
  family      = var.parameter_group_family
  description = "PrestaShop tuning for ${var.name_prefix}"

  parameter {
    name  = "character_set_server"
    value = "utf8mb4"
  }

  parameter {
    name  = "collation_server"
    value = "utf8mb4_unicode_ci"
  }

  parameter {
    name         = "max_allowed_packet"
    value        = "67108864"
    apply_method = "immediate"
  }

  lifecycle {
    create_before_destroy = true
  }

  tags = var.tags
}

resource "aws_db_instance" "this" {
  identifier     = "${var.name_prefix}-mysql"
  engine         = "mysql"
  engine_version = var.engine_version
  instance_class = var.instance_class

  db_name  = var.database_name
  username = var.master_username
  password = random_password.master.result
  port     = 3306

  allocated_storage     = var.allocated_storage
  max_allocated_storage = var.max_allocated_storage > 0 ? var.max_allocated_storage : null
  storage_type          = "gp3"
  storage_encrypted     = true

  db_subnet_group_name   = aws_db_subnet_group.this.name
  vpc_security_group_ids = var.security_group_ids
  parameter_group_name   = aws_db_parameter_group.this.name
  multi_az               = var.multi_az
  publicly_accessible    = false

  backup_retention_period    = var.backup_retention_period
  backup_window              = "02:00-03:00"
  maintenance_window         = "sun:03:30-sun:04:30"
  auto_minor_version_upgrade = true
  copy_tags_to_snapshot      = true

  performance_insights_enabled    = var.performance_insights_enabled
  enabled_cloudwatch_logs_exports = ["error", "slowquery"]

  deletion_protection       = var.deletion_protection
  skip_final_snapshot       = var.skip_final_snapshot
  final_snapshot_identifier = var.skip_final_snapshot ? null : "${var.name_prefix}-mysql-final-${random_id.snapshot.hex}"
  apply_immediately         = true

  tags = merge(var.tags, { Name = "${var.name_prefix}-mysql" })
}

# The password is generated by Terraform and handed over through Secrets
# Manager: it is never written to a tfvars file, never printed by an output and
# never copied into the Ansible repository. The instances read it at deploy time
# with their own IAM role.
resource "aws_secretsmanager_secret" "db" {
  name_prefix             = "${var.name_prefix}/database/"
  description             = "MySQL credentials of the ${var.name_prefix} PrestaShop database"
  recovery_window_in_days = var.secret_recovery_window_days

  tags = merge(var.tags, { Name = "${var.name_prefix}-db-credentials" })
}

resource "aws_secretsmanager_secret_version" "db" {
  secret_id = aws_secretsmanager_secret.db.id

  secret_string = jsonencode({
    engine   = "mysql"
    host     = aws_db_instance.this.address
    port     = aws_db_instance.this.port
    dbname   = var.database_name
    username = var.master_username
    password = random_password.master.result
  })
}
